name: lava
channels:
  - defaults
  - conda-forge
dependencies:
  - alembic=1.13.2
  - anyio=4.2.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - black=24.4.2
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=4.1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - colorlog=6.8.2
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - filelock=3.13.1
  - flake8=7.0.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.6.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - greenlet=3.0.3
  - idna=3.7
  - importlib-metadata=8.4.0
  - importlib_resources=6.4.4
  - ipykernel=6.28.0
  - ipython=8.25.0
  - isort=5.13.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libtiff=4.5.1
  - libtorch=2.4.0
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=18.1.8
  - loguru=0.5.3
  - lz4-c=1.9.4
  - mako=1.3.5
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mistune=2.0.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nomkl=3.0
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.21
  - openjpeg=2.5.2
  - openssl=3.3.2
  - optuna=4.0.0
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycodestyle=2.11.1
  - pycparser=2.21
  - pyflakes=3.2.0
  - pygments=2.15.1
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.4.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.10.6
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - send2trash=1.8.2
  - setuptools=72.1.0
  - shellingham=1.5.0
  - six=1.16.0
  - sleef=3.6.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.34
  - stack_data=0.2.0
  - sympy=1.13.2
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - torchvision=0.15.2
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typer=0.9.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.1
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - python-dotenv
    - ghp-import==2.1.0
    - markdown==3.7
    - mergedeep==1.3.4
    - mkdocs==1.6.1
    - mkdocs-get-deps==0.2.0
    - pathspec==0.12.1
    - python-dotenv==1.0.1
    - pyyaml-env-tag==0.1
    - watchdog==5.0.2
    - -e .
